@echo off
:loop
echo [%date% %time%] Starting localtunnel (delta-avtomaktab-uz)...
cmd.exe /c "npx -y localtunnel --port 8000 --subdomain delta-avtomaktab-uz > localtunnel_url.txt"
echo [%date% %time%] Localtunnel exited. Trying fallback SSH tunnel (serveo.net)...
cmd.exe /c "ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -R 80:localhost:8000 serveo.net > localtunnel_url.txt"
echo [%date% %time%] Both tunnels exited. Restarting in 5 seconds...
timeout /t 5
goto loop
